# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNDBbv7g7cE5OUq4_fbb_PIun2EvPYYA
"""

no=int(input("enter tje num"))
if no>1:
  for i in range(2,no):
    if no % i == 0:
      print (no,"not prime")
      break;
  else:
   print(no,"prime")
else:
  print(no,"not ")

pip install bs4

from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import numpy as np
link=" https://www.amazon.in/OnePlus-Mirror-Black-128GB-Storage/product-reviews/B07DJHV6VZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page=requests.get(link)
page
soup=bs(page.content,"html.parser")
soup
names=soup.find_all("span",class_="a-profile-name")
names
cust_names=[]
for i in range(len(names)):
  cust_names.append(names[i].get_text())
len(cust_names)
df=pd.DataFrame()

df["Names"]=cust_names
df["Names"]









from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import numpy as np
link=" https://www.amazon.in/OnePlus-Mirror-Black-128GB-Storage/product-reviews/B07DJHV6VZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page=requests.get(link)
page
soup=bs(page.content,"html.parser")
soup
names=soup.find_all("span",class_="a-profile-name")
names
cust_names=[]
for i in range(len(names)):
  cust_names.append(names[i].get_text())
len(cust_names)
df=pd.DataFrame()

df["Names"]=cust_names
df["Names"]

import requests
mink="https://www.amazon.in/OnePlus-Mirror-Black-128GB-Storage/product-reviews/B07DJHV6VZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page=requests.get(mink)
from bs4 import BeautifulSoup as bs

import pandas as pd
soup1=bs(page.content,"html.parser")



reviews=soup1.find_all("span",class_="a-size-base review-text review-text-content")


cust_reviews=[""]
for i in range(len(reviews)):
  cust_reviews.append(reviews[i].get_text())

cust_reviews=[i.strip("\n")for i in cust_reviews]


len(cust_reviews)

df=pd.DataFrame()

df["reviews"]=cust_reviews

df["names"]=cust_names
df

from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import numpy as np
link=" https://www.amazon.in/OnePlus-Mirror-Black-128GB-Storage/product-reviews/B07DJHV6VZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page=requests.get(link)
page
soup=bs(page.content,"html.parser")
soup
names=soup.find_all("span",class_="a-profile-name")
names
cust_names=[]
for i in range(len(names)):
  cust_names.append(names[i].get_text())
len(cust_names)
df=pd.DataFrame()

df["Names"]=cust_names
df
from google.colab import files
df.to_csv('output.csv', encoding = 'utf-8-sig') 
files.download('output.csv')